# Generated by Django 5.2.8 on 2026-01-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentspace',
            name='image_url',
        ),
        migrations.AddField(
            model_name='rentspace',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rent_spaces/'),
        ),
        migrations.DeleteModel(
            name='Inquiry',
        ),
    ]
