# Generated by Django 5.2.8 on 2026-01-01 09:18

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_rentspace_image_url_rentspace_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentspace',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='rent_spaces/'),
        ),
    ]
